/** Execute original AndroidX tree traversal and direct ClickableNode consumption.
 * Layout nodes, modifier links, density, source flags, normal stylus bounds and
 * abstract interaction emission are explicit hosts, not a full Compose runtime.
 */
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';import {gzipSync,gunzipSync} from 'node:zlib';import {fileURLToPath} from 'node:url';
const root=path.resolve(fileURLToPath(new URL('../../',import.meta.url))),cache=path.join(root,'research/pointer-tree-generator'),runtime=path.join(root,'research/kotlin-runtime');fs.mkdirSync(cache,{recursive:true});
const read=name=>fs.readFileSync(path.join(root,name),'utf8').replaceAll('\r\n','\n'),sha=data=>crypto.createHash('sha256').update(data).digest('hex');
const sources=[];
for(const family of ['pointer','toolbar-alignment','ripple'])for(const entry of JSON.parse(read(`test/fixtures/androidx/${family}/sources.json`)).sources){const file=`test/fixtures/androidx/${family}/${entry.file}`;if(sha(fs.readFileSync(path.join(root,file)))!==entry.sha256)throw Error(file);sources.push({file,url:entry.url,sha256:entry.sha256});}
function block(text,marker){const start=text.indexOf(marker),open=text.indexOf('{',start);if(start<0)throw Error(marker);let depth=0;for(let end=open;end<text.length;end++){depth+=(text[end]==='{')-(text[end]==='}');if(!depth)return text.slice(start,end+1);}throw Error(marker);}
function expression(text,marker){const start=text.indexOf(marker);if(start<0)throw Error(marker);return text.slice(start,text.indexOf('\n',start));}
const coord=read('test/fixtures/androidx/pointer/NodeCoordinator.kt'),inner=read('test/fixtures/androidx/toolbar-alignment/InnerNodeCoordinator.kt'),click=read('test/fixtures/androidx/ripple/FoundationClickable.kt'),pointer=read('test/fixtures/androidx/pointer/PointerEvent.kt'),tap=read('test/fixtures/androidx/pointer/TapGestureDetector.kt');
const markers=['fun hitTest(','private fun Modifier.Node?.hit(','private fun Modifier.Node?.outOfBoundsHit(','private fun Modifier.Node?.hitNear(','private fun Modifier.Node?.speculativeHit(','protected fun withinLayerBounds(','protected fun isPointerInBounds(','private fun offsetFromEdge(','protected fun calculateMinimumTouchTargetPadding(','protected fun distanceInMinimumTouchTarget(','open fun hitTestChild('];
const relocated=text=>text.replaceAll('HitTestSource','TreeHitSource');
const policies=`package androidx.compose.foundation\nimport kotlin.math.*\ninternal open class TreeCoordinator(id:String,width:Int,height:Int,radius:Float,x:Float=0f,y:Float=0f,density:Float=1f,target:Float=48f,pointer:Boolean=true,clipping:Boolean=true,share:Boolean=false):TreeCoordinatorHost(id,width,height,radius,x,y,density,target,pointer,clipping,share){\n${markers.map(m=>relocated(block(coord,m))).join('\n').replace('open fun hitTestChild(','override fun hitTestChild(')}\n}\ninternal class TreeInnerCoordinator(id:String,width:Int,height:Int,radius:Float,x:Float=0f,y:Float=0f,density:Float=1f,target:Float=48f,pointer:Boolean=true,clipping:Boolean=true,share:Boolean=false):TreeCoordinator(id,width,height,radius,x,y,density,target,pointer,clipping,share){val layoutNode=TreeLayoutNode(this)\n${relocated(block(inner,'override fun hitTestChild('))}\n}\n`;
const units={
 'TreePolicies.kt':policies,
 'Bodies.kt':'package androidx.compose.foundation\nimport kotlin.math.abs\nimport kotlin.math.max\n'+[block(click,'internal open class ClickableNode('),block(tap,'internal fun PointerEvent.isChangedToDown('),block(pointer,'public fun PointerInputChange.isOutOfBounds(size: IntSize, extendedTouchPadding: Size)'),...['changedToDown','changedToDownIgnoreConsumed','changedToUp','changedToUpIgnoreConsumed'].map(name=>expression(pointer,'public fun PointerInputChange.'+name+'()'))].join('\n'),
 'Padding.kt':'package androidx.compose.foundation\nimport kotlin.math.max\nopen class OriginalPadding {\n'+block(click,'protected fun getExtendedTouchPadding(size: IntSize)')+'\nfun padding(size:IntSize)=getExtendedTouchPadding(size)\n}',
 'CoordinatorBodies.kt':'package androidx.compose.foundation\ninternal class OriginalCoordinator(width:Int,height:Int,radius:Float,density:Float,target:Float):CoordinatorHost(width,height,radius,density,target){\n'+[markers[0],...markers.slice(5,10)].map(marker=>block(coord,marker)).join('\n')+'\n}'
};
for(const file of ['ShapeContainingUtil','HitTestResult'])units[file+'.kt']=read('test/fixtures/androidx/pointer/'+file+'.kt').split('\n').filter(line=>!line.startsWith('import androidx.')).map(line=>line.startsWith('package ')?'package androidx.compose.foundation':line).join('\n');
const generated=Object.entries(units).map(([name,text])=>{const file=path.join(cache,name);fs.writeFileSync(file,text+'\n');return file;});
const hosts=['tools/androidx-button/Pointer.kt','tools/androidx-button/PointerHit.kt','tools/androidx-pointer-tree/PointerTreeHost.kt'],jar=path.join(cache,'oracle.jar'),stdlib=path.join(runtime,'stdlib.jar');
const compile=spawnSync('java',['-cp',path.join(runtime,'*'),'org.jetbrains.kotlin.cli.jvm.K2JVMCompiler','-no-stdlib','-no-reflect','-classpath',stdlib,'-jvm-target','1.8','-d',jar,...generated,...hosts.map(file=>path.join(root,file))],{encoding:'utf8'});if(compile.status)throw Error(compile.stderr||compile.error?.message||'compiler failed');
const run=spawnSync('java',['-cp',jar+path.delimiter+stdlib,'androidx.compose.foundation.PointerTreeHostKt'],{encoding:'utf8',maxBuffer:64*1024*1024});if(run.status)throw Error(run.stderr||run.error?.message||'native host failed');
const data=JSON.parse(run.stdout),json=JSON.stringify(data)+'\n',directory=path.join(root,'test/fixtures/androidx/pointer-tree'),fixture=path.join(directory,'tree-oracle.json.gz');
const provenance={revision:'a095da93f8e98dea8748ceed79ea8427aade245f',sources,generated:Object.fromEntries(Object.entries(units).map(([name,text])=>[name,sha(text+'\n')])),hosts:hosts.map(file=>({file,sha256:sha(fs.readFileSync(path.join(root,file)))})),output:sha(json),cases:data.length,scope:'Complete original normal-node coordinator callbacks, InnerNodeCoordinator child traversal, HitTestResult and direct ClickableNode body. Supplied layout/source/modifier/translation/density/flag/abstract-indication hosts; no complete Compose, CombinedClickableNode, generic/cut path, explicit expanded stylus bounds, interception, multi-pointer scheduling or raster.'};
fs.writeFileSync(path.join(cache,'tree-oracle.json'),json);fs.writeFileSync(path.join(cache,'provenance.json'),JSON.stringify(provenance,null,2)+'\n');
if(process.argv.includes('--check')){if(gunzipSync(fs.readFileSync(fixture)).toString()!==json)throw Error('native fixture differs');}else{fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(fixture,gzipSync(json));fs.writeFileSync(path.join(directory,'sources.json'),JSON.stringify(provenance,null,2)+'\n');}
console.log(`${data.length} original tree/consumption records; SHA-256 ${sha(json)}; ${process.argv.includes('--check')?'byte-identical reproduction':'fixture written'}. Explicit host boundaries retained.`);
