import fs from 'node:fs';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import crypto from 'node:crypto';
const root=fileURLToPath(new URL('../../',import.meta.url));
const cache=path.join(root,'research/progress-generator');fs.mkdirSync(cache,{recursive:true});
const runtime=path.join(root,'research/kotlin-runtime');
const cp=['research/shape-generator/generator.jar','research/kotlin-runtime/stdlib.jar','research/kotlin-runtime/collection.jar','research/kotlin-runtime/androidx-annotation.jar'].map(x=>path.join(root,x)).join(path.delimiter);
if(!fs.existsSync(path.join(root,'research/shape-generator/generator.jar')))throw new Error('Run python tools/androidx-shapes/generate.py to prepare the pinned graphics-shapes runtime.');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'tools/androidx-shapes/sources.json'),'utf8'));
for(const [name,entry]of Object.entries(manifest.sources)){
 const bytes=fs.readFileSync(path.join(root,'research/shape-generator/upstream',name));
 if(crypto.createHash('sha256').update(bytes).digest('hex')!==entry.sha256)throw new Error('Pinned source hash mismatch: '+name);
}
function run(args){const result=spawnSync('java',args,{cwd:root,encoding:'utf8',maxBuffer:16e6});if(result.status!==0)throw new Error(result.stderr);return result.stdout;}
run(['-cp',path.join(runtime,'*'),'org.jetbrains.kotlin.cli.jvm.K2JVMCompiler','-no-stdlib','-no-reflect','-classpath',cp,'-jvm-target','1.8','-d',path.join(cache,'export.jar'),fileURLToPath(new URL('Export.kt',import.meta.url))]);
const data=JSON.parse(run(['-cp',path.join(cache,'export.jar')+path.delimiter+cp,'ExportKt']));
const license=fs.readFileSync(path.join(root,'test/fixtures/androidx/progress-indicators/CircularWavyProgressModifiers.kt'),'utf8').split('package ')[0];
fs.writeFileSync(path.join(root,'src/tokens/progress-morphs.js'),license+'// Generated by tools/androidx-progress/generate.mjs from pinned AndroidX graphics-shapes.\n// Rotational wedges reproduce non-default counts; default 9 retains every source cubic.\nexport const progressMorphs = '+JSON.stringify(data)+';\n');
console.log('Generated circular progress Morph coefficients for 252 vertex counts.');
