import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import zlib from 'node:zlib';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),here=fileURLToPath(new URL('./',import.meta.url)),cache=path.join(root,'research/progress-runtime-generator'),numeric=path.join(root,'research/progress-circular-motion-generator'),runtime=path.join(root,'research/kotlin-runtime');fs.mkdirSync(cache,{recursive:true});
const read=file=>fs.readFileSync(path.join(root,file),'utf8').replace(/^\uFEFF/,'').replaceAll('\r\n','\n'),hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const coroutineHash='ad89c2892235e670f222d819cb3d81188143cb19a05b59df9889ae4269f5c70a';
if(hash(fs.readFileSync(path.join(runtime,'coroutines-1.9.0.jar')))!==coroutineHash)throw Error('Pinned coroutines1.9.0 SHA');
if(!read('test/fixtures/androidx/progress-runtime/libs.versions.toml').includes('kotlinCoroutines = "1.9.0"'))throw Error('Pinned AndroidX coroutine version');
// Reassemble numeric bodies from checked upstream inputs; a pre-existing cache
// is not an oracle input. The narrower numeric fixtures must remain unchanged.
const prepare=spawnSync(process.execPath,[path.join(here,'generate-circular-motion.mjs')],{cwd:root,encoding:'utf8',maxBuffer:12e6});if(prepare.status!==0)throw Error(prepare.stderr||prepare.stdout);
function block(text,marker){const start=text.indexOf(marker);if(start<0)throw Error('Missing '+marker);let end=text.indexOf('{',start)+1,depth=1;while(depth&&end<text.length){depth+=(text[end]==='{')-(text[end]==='}');end++;}if(depth)throw Error('Unclosed '+marker);return text.slice(start,end);}
const sources=[];for(const [directory,file]of [['test/fixtures/androidx/progress-runtime','sources.json'],['test/fixtures/androidx/progress-indicators','sources.json'],['test/fixtures/androidx/progress-indicators','circular-motion-sources.json']])for(const source of JSON.parse(read(directory+'/'+file)).sources){const name=directory+'/'+source.file;if(hash(fs.readFileSync(path.join(root,name)))!==source.sha256)throw Error('Original SHA '+name);sources.push({file:name,sha256:source.sha256});}
const original=file=>read('test/fixtures/androidx/progress-runtime/'+file),license=original('Animatable.kt').split('package ')[0];
for(const source of JSON.parse(read('test/fixtures/androidx/progress-indicators/circular-motion-oracle.meta.json')).sources){if(hash(fs.readFileSync(path.join(root,source.file)))!==source.sha256)throw Error('Original numeric SHA '+source.file);if(!sources.some(entry=>entry.file===source.file))sources.push(source);}
const strip=text=>text.replace(/^import androidx\.compose\.runtime\.(?:Stable|Immutable|annotation.RememberInComposition)\n/gm,'').replace(/^import androidx\.compose\.(?:runtime|animation.core|ui)\.internal\.JvmDefaultWithCompatibility\n/gm,'').replace(/^@(?:Stable|Immutable|JvmDefaultWithCompatibility|RememberInComposition|ExperimentalComposeApi)(?:\([^\n]*\))?\n/gm,'').replace(/^@OptIn\(ExperimentalComposeApi::class\)\n/gm,'');
const save=(file,text)=>fs.writeFileSync(path.join(cache,file),text);
for(const file of ['Animatable.kt','AnimationState.kt','AnimationVectors.kt','MotionDurationScale.kt','InfiniteAnimationPolicy.kt','AnimationEndReason.kt','PlatformInfiniteAnimationPolicy.kt'])save(file,strip(original(file)));
save('MonotonicFrameClock.kt',strip(original('MonotonicFrameClock.kt')).replace('public expect val DefaultMonotonicFrameClock: MonotonicFrameClock','public val DefaultMonotonicFrameClock: MonotonicFrameClock get()=error("Unused global frame clock")'));
save('Mutex.kt',strip(original('InternalMutatorMutex.kt')).replace('import androidx.compose.animation.core.internal.PlatformOptimizedCancellationException\n',''));
const converters=original('VectorConverters.kt'),interfaceStart=converters.indexOf('public interface TwoWayConverter'),interfaceEnd=converters.indexOf('internal inline fun lerp',interfaceStart),floatGetter=converters.slice(converters.indexOf('public val Float.Companion.VectorConverter:'),converters.indexOf('/** A [TwoWayConverter] that converts [Int]'));
const floatValue=converters.slice(converters.indexOf('private val FloatToVector:'),converters.indexOf('private val IntToVector:'));
save('Converters.kt',license+'package androidx.compose.animation.core\n'+converters.slice(interfaceStart,interfaceEnd)+floatGetter+floatValue);
const animation=original('Animation.kt'),targetFactory=animation.slice(animation.indexOf('public fun <T, V : AnimationVector> TargetBasedAnimation('),animation.indexOf('/**\n * This is a convenient animation wrapper class'));
const durationGetter=animation.slice(animation.indexOf('internal val Animation<*, *>.durationMillis:'),animation.indexOf('internal const val MillisToNanos:'));
save('Animation.kt',license+'package androidx.compose.animation.core\n'+block(animation,'public interface Animation<')+'\n'+block(animation,'public class TargetBasedAnimation<')+'\n'+targetFactory+'\n'+durationGetter);
const suspended=original('SuspendAnimation.kt');save('Suspend.kt',license+'package androidx.compose.animation.core\nimport androidx.compose.runtime.withFrameNanos\nimport androidx.compose.ui.MotionDurationScale\nimport kotlin.coroutines.CoroutineContext\nimport kotlin.coroutines.coroutineContext\nimport kotlinx.coroutines.CancellationException\n'+suspended.slice(suspended.indexOf('internal suspend fun <T, V : AnimationVector> AnimationState<T, V>.animate(')));
save('Spec.kt',license+'package androidx.compose.animation.core\n'+block(original('AnimationSpec.kt'),'public object AnimationConstants')+'\n'+block(original('AnimationSpec.kt'),'public interface AnimationSpec<'));
save('InfiniteTransitionOriginal.kt',license+'package androidx.compose.animation.core\nimport androidx.compose.runtime.*\nimport androidx.compose.runtime.collection.mutableVectorOf\nimport kotlinx.coroutines.flow.first\n'+block(original('InfiniteTransition.kt'),'public class InfiniteTransition').replace(/^    @Composable\n/gm,''));
// Numerical source assemblies are reused only after verifying their original bodies.
const origins=[['VectorizedOriginal.kt','test/fixtures/androidx/motion/VectorizedAnimationSpec.kt',['public interface VectorizedAnimationSpec<','public interface VectorizedFiniteAnimationSpec<','public interface VectorizedDurationBasedAnimationSpec<','public class VectorizedKeyframesSpec<','public class VectorizedInfiniteRepeatableSpec<']],['TweenOriginal.kt','test/fixtures/androidx/motion/FloatAnimationSpec.kt',['public class FloatTweenSpec(']],['Bezier.kt','test/fixtures/androidx/navigation-drawer/Bezier.kt',['public fun findFirstCubicRoot(','public fun computeCubicVerticalBounds(']],['Math.kt','test/fixtures/androidx/navigation-drawer/MathHelpers.kt',['public fun fastCbrt(','public fun lerp(start: Float,']]];
for(const [file,source,markers]of origins){const text=fs.readFileSync(path.join(numeric,file),'utf8').replaceAll('\r\n','\n'),upstream=read(source);for(const marker of markers)if(!text.includes(block(upstream,marker)))throw Error('Altered numerical body '+marker);save(file,text);}
for(const file of ['Easing.kt','Bridge.kt','SearchOriginal.kt','DescriptorsOriginal.kt','OffsetDescriptorOriginal.kt','DrawingRotationOriginal.kt'])save(file,fs.readFileSync(path.join(numeric,file),'utf8'));
let dsl=read('tools/androidx-progress/CircularMotionHost.kt');dsl=dsl.slice(dsl.indexOf('// These scalar descriptors'));
dsl=dsl.replace('typealias AnimationSpec<T> = HostSpec<T>\n','');
for(const [type,native]of [['HostSpec','VectorizedDurationBasedAnimationSpec'],['HostInfiniteSpec','VectorizedInfiniteRepeatableSpec']])dsl=dsl.replace('class '+type+'<T>(val native: '+native+'<AnimationVector1D>)','class '+type+'<T>(val native: '+native+'<AnimationVector1D>):AnimationSpec<T>{\n@Suppress("UNCHECKED_CAST") override fun <V:AnimationVector> vectorize(converter:TwoWayConverter<T,V>):VectorizedAnimationSpec<V> = native as VectorizedAnimationSpec<V>\n}');
save('DescriptorsHost.kt','package androidx.compose.animation.core\n'+dsl);
const cp=['stdlib.jar','collection.jar','androidx-annotation.jar','coroutines-1.9.0.jar'].map(name=>path.join(runtime,name)).join(path.delimiter);
const files=fs.readdirSync(cache).filter(name=>name.endsWith('.kt')).map(name=>path.join(cache,name)).concat(['RuntimeStateHost.kt','RuntimeVectorHost.kt','ProgressRuntimeHost.kt','RuntimeProbe.kt'].map(name=>path.join(here,name)));
const result=spawnSync('java',['-cp',path.join(runtime,'*'),'org.jetbrains.kotlin.cli.jvm.K2JVMCompiler','-no-stdlib','-no-reflect','-classpath',cp,'-jvm-target','1.8','-d',path.join(cache,'oracle.jar'),...files],{cwd:root,encoding:'utf8',maxBuffer:12e6});if(result.status!==0)throw Error(result.stderr||result.stdout);
const run=spawnSync('java',['-cp',path.join(cache,'oracle.jar')+path.delimiter+cp,'androidx.compose.animation.core.RuntimeProbeKt'],{cwd:root,encoding:'utf8',maxBuffer:12e6});if(run.status!==0)throw Error(run.stderr||run.stdout);console.log(run.stdout.trim());
const timeline=spawnSync('java',['-cp',path.join(cache,'oracle.jar')+path.delimiter+cp,'androidx.compose.animation.core.RuntimeProbeKt','timeline'],{cwd:root,encoding:'utf8',maxBuffer:12e6});if(timeline.status!==0)throw Error(timeline.stderr||timeline.stdout);
const rows=JSON.parse(timeline.stdout),bytes=Buffer.from(JSON.stringify(rows)+'\n'),fixture=path.join(root,'test/fixtures/androidx/progress-runtime/frame-timeline.json.gz');
const hosts=['generate-runtime.mjs','RuntimeStateHost.kt','RuntimeVectorHost.kt','ProgressRuntimeHost.kt','RuntimeProbe.kt','CircularMotionHost.kt'].map(file=>({file:'tools/androidx-progress/'+file,sha256:hash(fs.readFileSync(path.join(here,file)))}));
fs.writeFileSync(fixture,zlib.gzipSync(bytes,{level:9}));fs.writeFileSync(fixture.replace('.json.gz','.meta.json'),JSON.stringify({sha256:hash(bytes),count:rows.length,sources,hosts,coroutines:{version:'1.9.0',sha256:coroutineHash,url:'https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.9.0/kotlinx-coroutines-core-jvm-1.9.0.jar'},compiler:'Private cached Kotlin/JVM1.9.24; pinned AndroidX main catalog2.4.20 is not the executed build environment.',scope:'Complete unchanged Animatable/TargetBasedAnimation/AnimationState/MutatorMutex/SuspendAnimation and InfiniteTransition class/run/child bodies and native numerical bodies with real coroutines1.9.0 Job cancellation/completion. Plain scalar-state, immediate remember/LaunchedEffect launch, list storage and manual MonotonicFrameClock platform bindings; scale1 timeline only. No Compose snapshot/composition/cache scheduler, durationScale0 resume, Android dispatcher, Matrix/PathMeasure/raster or unused spring/decay paths.'},null,2)+'\n');
console.log('Generated '+rows.length+' original real coroutine/frame-loop progress states; decoded SHA '+hash(bytes));
