import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import zlib from 'node:zlib';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),here=fileURLToPath(new URL('./',import.meta.url)),directory='test/fixtures/androidx/text-field',cache=path.join(root,'research/text-field-layout-generator'),runtime=path.join(root,'research/kotlin-runtime');fs.mkdirSync(cache,{recursive:true});
const hash=bytes=>crypto.createHash('sha256').update(bytes).digest('hex'),read=file=>fs.readFileSync(path.join(root,file),'utf8').replaceAll('\r\n','\n'),sources=[];
for(const [dir,file]of[[directory,directory+'/sources.json'],[directory,directory+'/layout-input-sources.json'],['test/fixtures/androidx/toolbar-row','test/fixtures/androidx/toolbar-row/sources.json'],['test/fixtures/androidx/navigation-drawer','test/fixtures/androidx/navigation-drawer/sources.json'],['test/fixtures/androidx/progress-indicators','test/fixtures/androidx/progress-indicators/sources.json']]){
 const manifest=JSON.parse(read(file));if(manifest.revision&&manifest.revision!=='a095da93f8e98dea8748ceed79ea8427aade245f')throw Error('Original revision '+file);
 for(const entry of manifest.sources??Object.entries(manifest.files).map(([file,entry])=>({file,...entry}))){const path=dir+'/'+entry.file;if(hash(fs.readFileSync(root+'/'+path))!==entry.sha256)throw Error('Original SHA '+path);if(!sources.some(source=>source.path===path))sources.push({...entry,path});}
}
function block(text,marker){const start=text.indexOf(marker);if(start<0)throw Error('Missing original '+marker);const first=text.indexOf('{',start);let depth=0;for(let i=first;i<text.length;i++){if(text[i]==='{')depth++;else if(text[i]==='}'&&--depth===0)return text.slice(start,i+1);}throw Error('Unclosed original '+marker);}
const save=(file,text)=>fs.writeFileSync(path.join(cache,file),text),impl=read(directory+'/TextFieldImpl.kt'),defaults=read(directory+'/TextFieldDefaults.kt'),license=impl.slice(0,impl.indexOf('package '));
const policy=['private class TextFieldMeasurePolicy(','private class OutlinedTextFieldMeasurePolicy('].map(marker=>block(impl,marker).replace('private class','internal class'));
const alignmentGetters=['minimizedAlignment','expandedAlignment'].map(name=>{const start=impl.indexOf('internal val TextFieldLabelPosition.'+name),first=impl.indexOf('{',start);return impl.slice(start,first)+block(impl.slice(first),'{' );});
// The getter bodies and complete policy classes are unchanged; only visibility
// and namespace/import wiring permit the separate reference host to invoke them.
const motion=read('test/fixtures/androidx/progress-indicators/MotionTokens.kt'),start=motion.indexOf('inline val EasingEmphasizedAccelerateCubicBezier:'),end=motion.indexOf('\n\n',start);if(start<0||end<0)throw Error('Missing original height easing');
const utilities=read(directory+'/LayoutUtil.kt');save('Policies.kt',license+'package reference\nimport kotlin.math.*\nimport androidx.compose.ui.util.lerp as lerpInt\nimport androidx.compose.animation.core.*\n'+policy.join('\n')+'\n'+block(defaults,'public abstract class TextFieldLabelPosition private constructor()')+'\n'+alignmentGetters.join('\n')+'\n'+utilities.slice(utilities.indexOf('internal val IntrinsicMeasurable.layoutId:'))+'\n'+motion.slice(start,end)+'\n');
const alignment=read('test/fixtures/androidx/toolbar-row/Alignment.kt');save('Alignment.kt',license+'package reference\n'+alignment.slice(alignment.indexOf('public fun interface Alignment')));
const constraints=read('test/fixtures/androidx/toolbar-row/Constraints.kt');save('Constraints.kt',license+'package reference\nimport kotlin.jvm.JvmInline\nimport kotlin.math.*\n'+constraints.slice(constraints.indexOf('@Immutable\n@JvmInline')));
const easing=read('test/fixtures/androidx/navigation-drawer/Easing.kt').replaceAll('import androidx.compose.runtime.Immutable\n','').replaceAll('import androidx.compose.runtime.Stable\n','').replaceAll('@Stable\n','').replaceAll('@Immutable\n','');save('Easing.kt',easing);
const helpers=[['Bezier.kt','Bezier.kt',['private fun evaluateCubic(p0:','public fun evaluateCubic(p1:','public fun findFirstCubicRoot(','private fun findQuadraticRoots(','public fun computeCubicVerticalBounds(','private inline fun clampValidRootInUnitRange(','private fun writeValidRootInUnitRange(']],['Math.kt','MathHelpers.kt',['public fun fastCbrt(','public fun lerp(start: Float,']]];
const hosts=[];
for(const [file,original,markers]of helpers){let text=read('research/button-elevation-generator/'+file);const source=read('test/fixtures/androidx/navigation-drawer/'+original);for(const marker of markers)if(!text.includes(block(source,marker)))throw Error('Altered numerical helper '+marker);
 if(file==='Math.kt'){text=text.replace('package androidx.compose.ui.util\n','package androidx.compose.ui.util\nimport kotlin.math.roundToInt\n');text+='\n'+block(source,'public fun lerp(start: Int,')+'\nfun Double.fastRoundToInt()=roundToInt()\n';}
 save(file,text);hosts.push({path:'research/button-elevation-generator/'+file,sha256:hash(fs.readFileSync(root+'/research/button-elevation-generator/'+file)),scope:'Cached numerical assembly, unchanged original bodies checked before compilation; primitive helper bindings remain hosts.'});}
save('Bridge.kt',read('research/button-elevation-generator/Bridge.kt'));hosts.push({path:'research/button-elevation-generator/Bridge.kt',sha256:hash(fs.readFileSync(root+'/research/button-elevation-generator/Bridge.kt')),scope:'Easing precondition and unused animation interface hosts.'});
save('LineLimits.kt',license+'package reference\n'+read(directory+'/TextFieldLineLimits.kt').slice(read(directory+'/TextFieldLineLimits.kt').indexOf('public sealed interface TextFieldLineLimits')));
const run=args=>{const result=spawnSync('java',args,{cwd:root,encoding:'utf8',maxBuffer:32*1024*1024});if(result.status!==0)throw Error(result.stderr||result.stdout);return result.stdout;};
const cp=['stdlib.jar','androidx-annotation.jar','collection.jar'].map(file=>path.join(runtime,file)).join(path.delimiter),files=['Policies.kt','Alignment.kt','Constraints.kt','Easing.kt','Bezier.kt','Math.kt','Bridge.kt','LineLimits.kt'].map(file=>path.join(cache,file)).concat(['LayoutHost.kt','LayoutExport.kt'].map(file=>path.join(here,file)));
run(['-cp',path.join(runtime,'*'),'org.jetbrains.kotlin.cli.jvm.K2JVMCompiler','-no-stdlib','-no-reflect','-classpath',cp,'-jvm-target','1.8','-d',path.join(cache,'reference.jar'),...files]);
const rows=JSON.parse(run(['-cp',path.join(cache,'reference.jar')+path.delimiter+cp,'reference.LayoutExportKt'])),bytes=Buffer.from(JSON.stringify(rows)+'\n');
fs.writeFileSync(root+'/'+directory+'/layout.json.gz',zlib.gzipSync(bytes,{level:9}));fs.writeFileSync(root+'/'+directory+'/layout.meta.json',JSON.stringify({revision:'a095da93f8e98dea8748ceed79ea8427aade245f',count:rows.length,sha256:hash(bytes),sources,hosts:[...hosts,...['generate-layout.mjs','LayoutHost.kt','LayoutExport.kt'].map(file=>({path:'tools/androidx-text-field/'+file,sha256:hash(fs.readFileSync(path.join(here,file)))}))],scope:'Complete unchanged filled/outlined measurement, intrinsic and placement classes, Constraints and Alignment bodies, original label-position/line-limit classes and original Float/Int lerp/easing numeric bodies. Density1/State-free producers, static synthetic leaf/font/intrinsic records, MeasureScope/Placeable/layer/parent-data hosts. No full composable wrapper tree, native text shaping/input/IME/layout coordinator/cache/snapshot/runtime/raster.'},null,2)+'\n');
console.log('Generated '+rows.length+' original complete field measurement/placement records, decoded SHA '+hash(bytes));
