// Reconstruct finite animation originals from SHA-verified files, never a cache.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
export const sha256=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
export function originalBlock(text,marker){const start=text.indexOf(marker);if(start<0)throw Error(marker);let first=start,parens=0;for(;first<text.length;first++){if(text[first]==='(')parens++;else if(text[first]===')')parens--;else if(text[first]==='{'&&parens===0)break;}let end=first+1,depth=1;while(depth&&end<text.length){depth+=(text[end]==='{')-(text[end]==='}');end++;}if(depth)throw Error('Unclosed '+marker);return text.slice(start,end);}
export function prepareFiniteRuntime(root,cache){
 fs.mkdirSync(cache,{recursive:true});const read=file=>fs.readFileSync(path.join(root,file),'utf8').replaceAll('\r\n','\n'),sources=[];
 for(const source of JSON.parse(read('test/fixtures/androidx/progress-runtime/sources.json')).sources){const file='test/fixtures/androidx/progress-runtime/'+source.file;if(sha256(fs.readFileSync(path.join(root,file)))!==source.sha256)throw Error('Original SHA '+file);sources.push({...source,file});}
 for(const [name,entry]of Object.entries(JSON.parse(read('tools/androidx-motion/sources.json')))){const file='test/fixtures/androidx/motion/'+name;if(sha256(fs.readFileSync(path.join(root,file)))!==entry.sha256)throw Error('Original SHA '+file);sources.push({...entry,file});}
 const original=file=>read('test/fixtures/androidx/progress-runtime/'+file),license=original('Animatable.kt').slice(0,original('Animatable.kt').indexOf('*/')+2)+'\n';
 const strip=text=>text.replace(/^import androidx\.compose\.runtime\.(?:Stable|Immutable|annotation.RememberInComposition)\n/gm,'').replace(/^import androidx\.compose\.(?:runtime|animation.core|ui)\.internal\.JvmDefaultWithCompatibility\n/gm,'').replace(/^@(?:Stable|Immutable|JvmDefaultWithCompatibility|RememberInComposition|ExperimentalComposeApi)(?:\([^\n]*\))?\n/gm,'').replace(/^@OptIn\(ExperimentalComposeApi::class\)\n/gm,'');
 const files=[];const save=(name,text)=>{const file=path.join(cache,name);fs.writeFileSync(file,text);files.push(file);};
 for(const file of ['Animatable.kt','AnimationState.kt','AnimationVectors.kt','MotionDurationScale.kt','InfiniteAnimationPolicy.kt','AnimationEndReason.kt','PlatformInfiniteAnimationPolicy.kt'])save(file,strip(original(file)));
 save('MonotonicFrameClock.kt',strip(original('MonotonicFrameClock.kt')).replace('public expect val DefaultMonotonicFrameClock: MonotonicFrameClock','public val DefaultMonotonicFrameClock: MonotonicFrameClock get()=error("Unused global frame clock")'));
 save('InternalMutex.kt',strip(original('InternalMutatorMutex.kt')).replace('import androidx.compose.animation.core.internal.PlatformOptimizedCancellationException\n',''));
 const converters=original('VectorConverters.kt'),a=converters.indexOf('public interface TwoWayConverter'),b=converters.indexOf('internal inline fun lerp',a);
 save('Converters.kt',license+'package androidx.compose.animation.core\nimport androidx.compose.ui.unit.Dp\n'+converters.slice(a,b)+converters.slice(converters.indexOf('public val Float.Companion.VectorConverter:'),converters.indexOf('/** A [TwoWayConverter] that converts [Int]'))+converters.slice(converters.indexOf('private val FloatToVector:'),converters.indexOf('private val IntToVector:'))+converters.slice(converters.indexOf('public val Dp.Companion.VectorConverter:'),converters.indexOf('/** A type converter that converts a [DpOffset]'))+converters.slice(converters.indexOf('private val DpToVector:'),converters.indexOf('/** A type converter that converts a [DpOffset]',converters.indexOf('private val DpToVector:'))));
 const animation=original('Animation.kt');save('Animation.kt',license+'package androidx.compose.animation.core\n'+originalBlock(animation,'public interface Animation<')+'\n'+originalBlock(animation,'public class TargetBasedAnimation<')+'\n'+animation.slice(animation.indexOf('public fun <T, V : AnimationVector> TargetBasedAnimation('),animation.indexOf('/**\n * This is a convenient animation wrapper class'))+'\n'+animation.slice(animation.indexOf('internal val Animation<*, *>.durationMillis:'),animation.indexOf('internal const val MillisToNanos:')));
 const suspended=original('SuspendAnimation.kt');save('Suspend.kt',license+'package androidx.compose.animation.core\nimport androidx.compose.runtime.withFrameNanos\nimport androidx.compose.ui.MotionDurationScale\nimport kotlin.coroutines.CoroutineContext\nimport kotlin.coroutines.coroutineContext\nimport kotlinx.coroutines.CancellationException\n'+suspended.slice(suspended.indexOf('internal suspend fun <T, V : AnimationVector> AnimationState<T, V>.animate(')));
 const spec=read('test/fixtures/androidx/motion/AnimationSpec.kt'),vectorized=read('test/fixtures/androidx/motion/VectorizedAnimationSpec.kt'),float=read('test/fixtures/androidx/motion/FloatAnimationSpec.kt');
 save('Specs.kt',license+'package androidx.compose.animation.core\n'+['public object AnimationConstants','public interface AnimationSpec<','public interface FiniteAnimationSpec<','public interface DurationBasedAnimationSpec<','public class SpringSpec<','public class SnapSpec<','private fun <T, V : AnimationVector> TwoWayConverter<T, V>.convert('].map(marker=>originalBlock(spec,marker)).join('\n')+'\n'+spec.slice(spec.indexOf('public fun <T> spring('),spec.indexOf('\n\n',spec.indexOf('): SpringSpec<T> = SpringSpec('))));
 save('Vectorized.kt',license+'package androidx.compose.animation.core\n'+['public interface VectorizedAnimationSpec<','public interface VectorizedFiniteAnimationSpec<','public interface VectorizedDurationBasedAnimationSpec<','public object Spring','internal interface Animations','public class VectorizedSpringSpec<','private object DefaultSpringAnimations','private fun <V : AnimationVector> createSpringAnimations(','public class VectorizedFloatAnimationSpec<','public class VectorizedSnapSpec<'].map(marker=>originalBlock(vectorized,marker)).join('\n'));
 save('Float.kt',license+'package androidx.compose.animation.core\nconst val MillisToNanos=1_000_000L\n'+originalBlock(float,'public interface FloatAnimationSpec :')+'\n'+originalBlock(float,'public class FloatSpringSpec('));
 for(const file of ['SpringSimulation.kt','SpringEstimation.kt'])save(file,read('test/fixtures/androidx/motion/'+file));save('FloatPackingHost.kt',read('tools/androidx-motion/FloatPacking.kt')+'\nfun Double.fastIsFinite()=isFinite()\n');
 return {files,sources,read,save,license};
}
