import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
import {preparePackedColorRuntime} from './packed-runtime.mjs';import {sha256} from '../androidx-motion/finite-runtime.mjs';
const root=fileURLToPath(new URL('../../',import.meta.url)),runtime=path.join(root,'research/kotlin-runtime'),cache=path.join(root,'research/color-packed-generator'),fixture=path.join(root,'test/fixtures/androidx/color/packed');
const prepared=preparePackedColorRuntime(root,cache),hosts=['tools/androidx-color/generate-packed.mjs','tools/androidx-color/packed-runtime.mjs','tools/androidx-color/AnnotationHost.kt','tools/androidx-color/AnimationPreconditionHost.kt','tools/androidx-color/PackedColorProbe.kt','tools/androidx-color/ColorSpaceDataProbe.kt','tools/androidx-motion/finite-runtime.mjs'];
const libraries=['stdlib.jar','collection.jar','androidx-annotation.jar'].map(file=>({file,sha256:sha256(fs.readFileSync(path.join(runtime,file)))})),cp=libraries.map(({file})=>path.join(runtime,file)).join(path.delimiter);
const run=args=>{const r=spawnSync('java',args,{cwd:root,encoding:'utf8',maxBuffer:64e6});if(r.status!==0)throw Error(r.stderr||r.stdout);return r.stdout;};
run(['-cp',path.join(runtime,'*'),'org.jetbrains.kotlin.cli.jvm.K2JVMCompiler','-Xuse-k2','-no-stdlib','-no-reflect','-classpath',cp,'-jvm-target','1.8','-d',path.join(cache,'reference.jar'),...prepared.files,...hosts.filter(file=>file.endsWith('.kt')).map(file=>path.join(root,file))]);
const rows=JSON.parse(run(['-cp',path.join(cache,'reference.jar')+path.delimiter+cp,'androidx.compose.ui.graphics.PackedColorProbeKt'])),bytes=Buffer.from(JSON.stringify(rows)+'\n');
const data=JSON.parse(run(['-cp',path.join(cache,'reference.jar')+path.delimiter+cp,'androidx.compose.ui.graphics.colorspace.ColorSpaceDataProbeKt']));
const generated=Buffer.from('/* Copyright 2019-2021 The Android Open Source Project\n * Licensed under the Apache License, Version 2.0.\n * Generated from complete original ColorSpaces/Rgb/Connector/Oklab bodies at\n * a095da93f8e98dea8748ceed79ea8427aade245f. This is color-space math, not a theme palette.\n * Reproduce: node tools/androidx-color/generate-packed.mjs --check\n */\nexport const NATIVE_COLOR_SPACES='+JSON.stringify(data)+';\n');
const meta={revision:'a095da93f8e98dea8748ceed79ea8427aade245f',count:rows.length,sha256:sha256(bytes),sources:prepared.sources,hosts:hosts.map(file=>({file,sha256:sha256(fs.readFileSync(path.join(root,file)))})),compiler:{version:'1.9.24',frontend:'K2 experimental language2.0',originalBuildVersion:'2.4.20'},libraries,scope:'Complete unchanged Color.kt/Float16.kt, ColorSpace/ColorSpaces/Rgb/Connector/RenderIntent/TransferParameters/WhitePoint/Adaptation/Illuminant/Lab/Xyz/Oklab, MathHelpers and inline packing/JVM actual bit/round bodies, original ColorVectorConverter/TwoWayConverter/AnimationVectors. Expect/actual keywords and annotation leaves alone are bound for standalone JVM. Original bundled collection connector cache runs, SHA recorded. Direct construction, all half patterns/finite rounding boundaries, all20 native color spaces/all4 rendering intents, vector conversion/clamp/round trip. No finite coroutine animation/Compose component tree, native rendering/OS or full original compiler build in this probe.'};
meta.generated={file:'src/motion/color-spaces.generated.js',sha256:sha256(generated)};
for(const [full,value]of [[path.join(fixture,'values.json'),bytes],[path.join(fixture,'values.meta.json'),Buffer.from(JSON.stringify(meta,null,2)+'\n')],[path.join(root,meta.generated.file),generated]]){if(process.argv.includes('--check')){if(!fs.readFileSync(full).equals(value))throw Error('Reference drift '+full);}else fs.writeFileSync(full,value);}
console.log('Native packed Color/space: '+rows.length+' records, SHA '+sha256(bytes));
