import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {preparePackedColorRuntime} from './packed-runtime.mjs';import {prepareFiniteRuntime,originalBlock,sha256} from '../androidx-motion/finite-runtime.mjs';
const group=process.argv.includes('--group'),consumer=process.argv.includes('--consumers'),prefix=group?'group-runtime':consumer?'consumer-runtime':'runtime';
const probe=group?'tools/androidx-text-field/BroadcastGroupRuntimeProbe.kt':consumer?'tools/androidx-color/PackedColorConsumerProbe.kt':'tools/androidx-color/PackedColorRuntimeProbe.kt';
const root=fileURLToPath(new URL('../../',import.meta.url)),runtime=path.join(root,'research/kotlin-runtime'),cache=path.join(root,'research/color-packed-'+prefix+'-generator'),fixture=path.join(root,'test/fixtures/androidx/color/packed');
const finite=prepareFiniteRuntime(root,cache),packed=preparePackedColorRuntime(root,cache),{read,save,license}=finite;
for(const manifest of ['container-runtime-sources.json','container-broadcast-sources.json'])for(const source of JSON.parse(read('test/fixtures/androidx/text-field/'+manifest)).sources){const file='test/fixtures/androidx/text-field/'+source.file;if(sha256(fs.readFileSync(path.join(root,file)))!==source.sha256)throw Error('Original SHA '+file);finite.sources.push({...source,file});}
for(const file of ['AndroidUiDispatcher.android.kt','AndroidUiFrameClock.android.kt','BroadcastFrameClock.kt','AwaiterQueue.kt','CancellationHandle.kt','AnimationTooling.kt'])save(file,read('test/fixtures/androidx/text-field/'+file));
const asState=read('test/fixtures/androidx/motion/AnimateAsState.kt');save('AsState.kt',license+'package androidx.compose.animation.core\nimport androidx.compose.animation.core.tooling.AnimateValueAsStateToolingHandle\nimport androidx.compose.runtime.*\nimport androidx.compose.ui.unit.*\nimport kotlinx.coroutines.*\nprivate val defaultAnimation=spring<Float>()\nprivate const val DefaultFloatVisibilityThreshold=.01f\nprivate val dpDefaultSpring=spring<Dp>(visibilityThreshold=Dp.VisibilityThreshold)\n'+originalBlock(asState,'public fun animateFloatAsState(')+'\n'+originalBlock(asState,'public fun animateDpAsState(')+'\n'+originalBlock(asState,'public fun <T, V : AnimationVector> animateValueAsState(')+'\n'+originalBlock(asState,'private class AnimateAsState<'));
const single=read('test/fixtures/androidx/text-field/SingleValueAnimation.kt');save('SingleColor.kt',license+'package androidx.compose.animation\nimport androidx.compose.animation.core.*\nimport androidx.compose.runtime.*\nimport androidx.compose.ui.graphics.Color\nprivate val colorDefaultSpring=spring<Color>()\n'+originalBlock(single,'public fun animateColorAsState('));
const effects=read('test/fixtures/androidx/text-field/Effects.kt'),start=effects.indexOf('internal fun createCompositionCoroutineScope('),end=effects.indexOf('\n/**',start),exceptionStart=effects.indexOf('private class ExitedCompositionCancellationException'),exceptionEnd=effects.indexOf('\n/**',exceptionStart);save('RememberedScope.kt',license+'package androidx.compose.runtime\nimport androidx.compose.runtime.platform.makeSynchronizedObject\nimport androidx.compose.runtime.platform.synchronized\nimport kotlin.coroutines.*\nimport kotlinx.coroutines.*\n'+effects.slice(exceptionStart,exceptionEnd)+'\n'+originalBlock(effects,'private class CancelledCoroutineContext')+'\n'+originalBlock(effects,'internal class RememberedCoroutineScope(')+'\n@PublishedApi\n'+effects.slice(start,end)+'\n'+originalBlock(effects,'public inline fun rememberCoroutineScope('));
const hosts=['tools/androidx-color/generate-runtime.mjs','tools/androidx-color/packed-runtime.mjs','tools/androidx-color/AnnotationHost.kt',probe,'tools/androidx-motion/finite-runtime.mjs','tools/androidx-picker/ClockRuntimeHost.kt',...['ContainerBroadcastCompositionHost.kt','ContainerValueHost.kt','AndroidLooperHost.kt','AndroidChoreographerHost.kt','AndroidHandlerCompatHost.kt','AndroidClockHost.kt','BroadcastAtomicHost.kt','BroadcastSynchronizationHost.kt','BroadcastClockHost.kt'].map(file=>'tools/androidx-text-field/'+file)];
const libraries=['stdlib.jar','collection.jar','androidx-annotation.jar','coroutines-1.9.0.jar'].map(file=>({file,sha256:sha256(fs.readFileSync(path.join(runtime,file)))})),cp=libraries.map(({file})=>path.join(runtime,file)).join(path.delimiter),files=[...new Set([...finite.files.filter(file=>!file.endsWith('FloatPackingHost.kt')),...packed.files.filter(file=>!file.endsWith('TwoWayConverter.kt')),...hosts.filter(file=>file.endsWith('.kt')).map(file=>path.join(root,file))])];
const run=args=>{const r=spawnSync('java',args,{cwd:root,encoding:'utf8',maxBuffer:128e6});if(r.status!==0)throw Error(r.stderr||r.stdout);return r.stdout;};run(['-cp',path.join(runtime,'*'),'org.jetbrains.kotlin.cli.jvm.K2JVMCompiler','-Xuse-k2','-no-stdlib','-no-reflect','-classpath',cp,'-jvm-target','1.8','-d',path.join(cache,'reference.jar'),...files]);
if(libraries.find(entry=>entry.file==='coroutines-1.9.0.jar').sha256!=='ad89c2892235e670f222d819cb3d81188143cb19a05b59df9889ae4269f5c70a')throw Error('Pinned coroutine SHA');
const rows=JSON.parse(run(['-cp',path.join(cache,'reference.jar')+path.delimiter+cp,'androidx.compose.animation.core.'+(group?'BroadcastGroupRuntimeProbeKt':consumer?'PackedColorConsumerProbeKt':'PackedColorRuntimeProbeKt')])),bytes=Buffer.from(JSON.stringify(rows,(key,value)=>Object.is(value,-0)?JSON.rawJSON('-0'):value)+'\n');
const meta={revision:'a095da93f8e98dea8748ceed79ea8427aade245f',count:rows.length,sha256:sha256(bytes),sources:[...finite.sources,...packed.sources],hosts:hosts.map(file=>({file,sha256:sha256(fs.readFileSync(path.join(root,file)))})),compiler:{version:'1.9.24',frontend:'K2 experimental language2.0',originalBuildVersion:'2.4.20'},libraries,scope:'Complete original packed Color/ColorSpaces/all conversions/Float16/math/JVM bindings and ColorVectorConverter with Color animate-as-state/value wrappers/AnimateAsState, finite Animatable/spring/snap/AnimationState/TargetBasedAnimation/SuspendAnimation/internal mutex, original remembered coroutine scope, BroadcastFrameClock/AwaiterQueue and AndroidUiDispatcher. Full native packed color is used, no Float Color proxy. Plain scalar State/slots/commit/frame/handler/OS/synchronization and annotation/Dp leaves are hosts. Full Recomposer/snapshot/real component trees/OS delay/native raster/original compiler build remain separate.'};
for(const [file,value]of [[prefix+'.json',bytes],[prefix+'.meta.json',Buffer.from(JSON.stringify(meta,null,2)+'\n')]]){const target=path.join(fixture,file);if(process.argv.includes('--check')){if(!fs.readFileSync(target).equals(value))throw Error('Reference drift '+file);}else fs.writeFileSync(target,value);}
console.log('Native packed Color applying runtime: '+rows.length+' snapshots, SHA '+sha256(bytes));
